version: "3"

volumes:
  redis_data:

services:
  mail-sender:
    image: mail-sender-image
    container_name: mail-sender
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

  redis:
    image: bitnami/redis:latest
    container_name: mail-sender-redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=redispasswd
    volumes:
      - redis_data:/bitnami/redis/data
